### ISSUE TITLE
code Highlight

### ISSUE THREAD

**Issue by glazec** [glazec/hexo-cheatsheets#13]
The bash code seems not to highlight properly.

**Comment by TianyiShi2001** [comment]
In my case bash code seems to be highlighted property but for python code, it is neither highlighted nor laid out property.

<img width="1263" alt="Screenshot 2021-03-10 at 19 08 35" src="https://user-images.githubusercontent.com/38644266/110683877-7ee92780-8217-11eb-9d1f-e77dd3090375.png">
<img width="598" alt="Screenshot 2021-03-10 at 19 08 43" src="https://user-images.githubusercontent.com/38644266/110683889-827cae80-8217-11eb-8801-d4e24d589aa0.png">

Here's my config:

```yml
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
```
